apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      serviceAccountName: ecomm-app-sa
      containers:
        - name: php
          image: iancrichardson10/php:7.2.10-fpm
          imagePullPolicy: Always
