FROM nginx:1

# Copy custom configuration file
COPY src/default.conf /etc/nginx/conf.d/default.conf

# Copy website files
COPY src/www /usr/share/nginx/html

RUN mkdir -p /usr/share/nginx/html/images

# Copy images
COPY src/images /usr/share/nginx/html/images

RUN chmod 644 /usr/share/nginx/html/images/*

RUN chown www-data:www-data /usr/share/nginx/html/images/*

RUN chmod 755 /usr/share/nginx/html/images

# Expose the port
EXPOSE 80
